### PR TITLE
Make it an Expo app

### LINKED ISSUE #9: Make it an Expo app
Biggest benefit here is that devs can get up and running really really fast:
* Scan QR code in Expo app to launch dev app
* Push single button to launch simulator
* Easily switch dev/production mode
* etc.

Steps required (from [Expo FAQ](https://docs.expo.io/versions/latest/introduction/faq.html#how-do-i-get-my-existing-react-native-project-running-with-expo)):
1. `npm install -g exp`
1. Move project files out of the way
1. `exp init`
1. Move javascript source files back, taking care to not blow away things that `exp init`
1. `yarn add [--dev]` the things in the old `package.json`

### PR DESCRIPTION
**Pull request by brettdh**
- Verified that the app and storybook still work
- Updated readme

Closes #9.

### CODE REVIEW

**Comment by CaleCrawford** [comment]
I love this. It all works great for me. I attached the app to my vscode debugger and got it running.
Trying to understand the expo/react-native relationship. Is there a reason why:
- We are loading RN through expo zip in package.json?
- We are using RN sdk 25? Is that different than the v0.52 release?

Do you want me to commit my vscode launch.json for anyone else wanting to debug with vscode or should I add that to the .gitignore? My only reference to this is looking at https://github.com/wearehive/project-guidelines and their .gitignore which includes the launch.json for vscode https://github.com/wearehive/project-guidelines/blob/master/.gitignore. 

Once we decide on that would you like me to merge this branch?

**Comment by brettdh** [comment]
@CaleCrawford 

> Do you want me to commit my vscode launch.json for anyone else wanting to debug with vscode or should I add that to the .gitignore?

I'm guessing that vscode's `launch.json` should be in `.gitignore`, since it seems particular to your local environment. 

> Trying to understand the expo/react-native relationship. Is there a reason why:
> - We are loading RN through expo zip in package.json?
> - We are using RN sdk 25? Is that different than the v0.52 release?

You're looking at the **Expo** SDK level, not react-native:
https://docs.expo.io/versions/latest/introduction/faq.html#why-does-expo-use-a-fork-of-react-native

> Once we decide on that would you like me to merge this branch?

Unfortunately this branch is based off a bunch of others - so if you want this to land soon, please also review and approve my other PRs ;) and then I'll take care of merging the pile. (I didn't intend to hold this up on that stuff, since it's ostensibly unrelated - but it's tricky to deal with the conflicts otherwise, especially conflicts in `package.json`/`yarn.lock`.)

**Comment by brettdh** [comment]
Also, please make sure you approve each PR when you're done looking at it so that I can merge it later.

**Comment by brettdh** [comment]
Clarifying: it doesn't require approval *yet* because it's based off another branch, but later when I go to merge it into master, it will require at least one approved review.

**Comment by CaleCrawford** [comment]
Sweet thanks for clarifying. I'll go through the other 6 PR's look through/test and approve.

**Review by CaleCrawford — APPROVED** [review]
Excited for this

**Pull request merged**
