### PR TITLE
Add Mastodon and Slack links

### LINKED ISSUE #101: Replace comment sections with links to external discussion foums
This issue needs a [Quest](https://medium.com/@trek/source-quest-ff7d227d8fed).

The goal is to give the developer who implements this feature the proper context and
starting point so as to make it easy for anyone to get started quickly, regardless of background,
domain expertise, or familiarity with a particular part of the code.

### PR DESCRIPTION
**Pull request by brettdh**
## Description
For the moment, it appears that Mastodon and Slack are the main social forums, so that's what I've used to replace the comments sections for now. Mike is investigating other options for longer-form discussion, so we'll look at adding that/those once that launches.

- Mastodon links to social.theliturgists.com
- Slack links to the signup form
  - We may be able to do an auto-signup here, but it's more complicated.

## Motivation and Context
We're launching without user accounts and comments, but we do want to point app users to the social forums that exist.

Closes #101.

## Screenshot
screen shot 2019-02-03 at 5 05 50 pm

### CODE REVIEW

**Comment by tannerhearne** [comment]
Hey @brettdh - I like it.  I've updated the two button designs.  Here are two SVGs.

[**Download the ZIP**](https://github.com/theliturgists/app/files/2825855/discussion-buttons.zip)

**Preview Images:**
slack-button-preview
mastadon-button-preview

**Comment by brettdh** [comment]
THANK YOU the mismatched baseline was driving me nuts but I just had to get something in there. I like these a lot.

**Comment by brettdh** [comment]
@tannerhearne For images other than icons, I've been using PNGs, which avoids common SVG-related issues with React Native. Could you convert these to PNGs?

**Comment by brettdh** [comment]
Actually, maybe I can just do it. The tool I was using for other SVGs didn't work; gotta dig up another method.

**Comment by brettdh** [comment]
I figured it out. 🙂

**Comment by brettdh** [comment]
@tannerhearne I'm not sure why, but the fonts got thicker when I converted to PNG (see updated screenshot). I didn't have the font, so I installed it from [here](https://www.google.com/get/noto/) before converting with [svgexport](https://www.npmjs.com/package/svgexport)... not sure if there's a better way, but that was the easiest for me 😕

**Comment by brettdh** [comment]
@tannerhearne merging for now; let me know if you have further button tweaks.

**Pull request merged**
